// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScrumBoard.DataAccess;

#nullable disable

namespace ScrumBoard.Migrations.UsageDataDb
{
    [DbContext(typeof(UsageDataDbContext))]
    [Migration("20231215230841_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ScrumBoard.Models.Entities.UsageData.BaseUsageDataEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Occurred")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UsageDataEvents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseUsageDataEvent");
                });

            modelBuilder.Entity("ScrumBoard.Models.Entities.UsageData.AuthenticationUsageEvent", b =>
                {
                    b.HasBaseType("ScrumBoard.Models.Entities.UsageData.BaseUsageDataEvent");

                    b.Property<int>("AuthenticationEventType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("AuthenticationUsageEvent");
                });

            modelBuilder.Entity("ScrumBoard.Models.Entities.UsageData.ViewLoadedUsageEvent", b =>
                {
                    b.HasBaseType("ScrumBoard.Models.Entities.UsageData.BaseUsageDataEvent");

                    b.Property<int>("LoadedViewUsageEventType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("ViewLoadedUsageEvent");
                });

            modelBuilder.Entity("ScrumBoard.Models.Entities.UsageData.ProjectViewLoadedUsageEvent", b =>
                {
                    b.HasBaseType("ScrumBoard.Models.Entities.UsageData.ViewLoadedUsageEvent");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResourceId")
                        .HasColumnType("bigint");

                    b.HasDiscriminator().HasValue("ProjectViewLoadedUsageEvent");
                });

            modelBuilder.Entity("ScrumBoard.Models.Entities.UsageData.StudentGuideViewLoadedUsageEvent", b =>
                {
                    b.HasBaseType("ScrumBoard.Models.Entities.UsageData.ViewLoadedUsageEvent");

                    b.Property<string>("ContentFileName")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("StudentGuideViewLoadedUsageEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
